#!/bin/bash
# Disable SSL verify
export GIT_SSL_NO_VERIFY=true

dotfiles=/data4/kietpham/00_dot
config=$dotfiles/config
tools=$dotfiles/tools

export PATH="$tools/nvim-0.10.0/bin:$PATH"				# Neovim
export PATH="$tools/node-v16.17.1/bin:$PATH"			# Nodejs
export PATH="$tools/python-3.10.7/bin:$PATH"			# Python
export PATH="$tools/ctags/bin:$PATH"					# Universal Ctags
export PATH="$tools/tmux-3.3a/bin:$PATH"				# Tmux
export PATH="$tools/cmake-3.25.0/bin:$PATH"				# Cmake
export PATH="$tools/tree-2.1.0/bin:$PATH"				# Tree show
export PATH="$tools/ripgrep-13.0.0:$PATH"				# Ripgrep
export PATH="$tools/bat-v0.22.1:$PATH"					# Bat
export PATH="$tools/fd-v8.4.0:$PATH"					# Finder
export PATH="$tools/ffmpeg:$PATH"					    # Video converter
export PATH="$tools/fzf:$PATH"					    	# Fuzzy finder
export PATH="$tools/zsh-5.9/bin:$PATH"					# ZSH
export PATH="$tools:$PATH"								# Lazygit
export PATH="$tools/delta-0.14.0:$PATH"					# Delta (git diff)
export PATH="$config/mason/bin:$PATH"

# Enable color on tmux
alias tmux="TERM=xterm-256color tmux"
alias ohmybash=". ~/.bash_prompt"

# Change nvim to git default editor
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    alias nvim=nvr -cc split --remote-wait +'set bufhidden=wipe'
fi

if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
    export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
    export VISUAL="nvim"
    export EDITOR="nvim"
fi

# Ip declaration
lab208=kietpham@172.29.145.208
lab12=kietpham@192.168.5.12
lab16=rvc@192.168.5.16
lab12_g2l=kietpham@192.168.5.12:/data1/tftpboot/kietpham/g2l
lab12_v2l=kietpham@192.168.5.12:/data1/tftpboot/kietpham/v2l
lab5_v2l=rvc@192.168.5.5:/data1/tftpboot/kietpham/v2l

# Workspace declaration
kietpham=/shsv/SS2/RSS3/36_kietpham/
mmp=/shsv/RCarSW2/Prj_RZG/01_projects/66-MMP
omx_src=/data4/kietpham/01_codec/01_OMX_Src/rzg-omx-codec/omx_src
omx_test=/data4/kietpham/01_codec/01_OMX_Src/omx_test
yocto=/data4/kietpham/03_yocto
toolchain=/data4/kietpham/04_toolchain/sdk-3.1.21/environment-setup-aarch64-poky-linux

# Export some variable
OMX_INC_DIR=${omx_src}/omx/bin/include
OMX_LIB_DIR=${omx_src}/omx/bin/lib
# export DESTDIR=${omx_test}/IT/IT2/build

# Some alias
alias nvim="$tools/nvim-0.10.0/bin/nvim"
alias 2scp='scp -oProxyCommand="'"ssh $lab208 nc %h %p"'"'

alias cd3="cd ../../../"
alias cd4="cd ../../../../"
alias cd5="cd ../../../../../"
alias cd6="cd ../../../../../../"
alias cd7="cd ../../../../../../../"
alias cd8="cd ../../../../../../../../"
alias cd9="cd ../../../../../../../../../"
