set -g mouse on

# start with window number 1
set -g base-index 1

# Notifying if other windows has activities
setw -g monitor-activity on

# Renumber windows on window close
set -g renumber-windows on

# Set RGB color for tmux
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Switch pane
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"
bind h if-shell "$is_vim" 'send-keys C-b h'  'select-pane -L'
bind j if-shell "$is_vim" 'send-keys C-b j'  'select-pane -D'
bind k if-shell "$is_vim" 'send-keys C-b k'  'select-pane -U'
bind l if-shell "$is_vim" 'send-keys C-b l'  'select-pane -R'

# Copy from tmux
bind C-S-c run "tmux save-buffer - | xclip -i -sel clipboard"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'imomaliev/tmux-keyboard-layout'

# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g status-right '#{keyboard_layout}'

source ~/.tmux/tokyonight.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
